Create wraesp.lua
LunexSan/ttt2-role_wra pull request #10
Opened 2020-07-31 06:29 UTC by Tekiad

wrath spanish translation

2020-10-25 07:57 UTC, LunexSan requested changes
Did you purposefully not translate the last line (L14)? please clarify that and tell me why, otherwise please translate that as well if possible^^

2020-10-25 22:48 UTC, Tekiad commented
> Did you purposefully not translate the last line (L14)? please clarify that and tell me why, otherwise please translate that as well if possible^^

Done n-n

2020-10-26 11:10 UTC, LunexSan commented
Thank you! I wasn't sure if you forgot, or didn't translate it for some reason i couldn't get my head around, thank you very much for your contribution! :)

2020-10-26 11:11 UTC, LunexSan approved these changes

2020-10-26 11:12 UTC, merged